import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppSidebar } from "@/components/AppSidebar";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import ReduxProvider from "@/components/ReduxProvider";
import SessionAuthProvider from "@/components/SessionAuthProvider";
import { auth } from "@/auth";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Pirate",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  // Fetch the session on the server
  const session = await auth();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReduxProvider>
          {/* Pass the session to SessionAuthProvider */}
          <SessionAuthProvider session={session}>
            <SidebarProvider>
              <div className="h-fit flex w-full">
                <AppSidebar />
                <main className="flex-1 min-h-screen bg-gradient-to-b from-slate-700 to-slate-600">
                  <SidebarTrigger className="sticky top-0" />
                  {children}
                </main>
              </div>
            </SidebarProvider>
          </SessionAuthProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
